security:
    encoders:
        FOS\UserBundle\Entity\User: sha512
        #Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                provider: fos_userbundle
            #     check_path: /demo/secured/login_check
            #     login_path: /demo/secured/login
            #logout:
            #    path:   /demo/secured/logout
            #    target: /demo/
            anonymous: ~
            #http_basic:
            #   realm: "Secured Demo Area"
    access_control:
        - {path: ^/admin, roles: ROLE_ADMIN}
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
