<?php

namespace Train\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findAllNewestFirst()
    {
        $query = $this->createQueryBuilder('p')
            ->orderBy('p.created')
            ->getQuery();
        
        return $query->getResult();
    }
}